const Actions = {
    start: '/start',
    change_lang: '/lang',
    change_lang_short: '/l',
    change_currency: '/currency',
    change_currency_short: '/c',
    help: '/help',
    help_short: '/h',
    guide: '/guide',
    guide_short: '/g',
    my_wallet: '/mywallet',
    my_wallet_short: '/mw',
    add_money: '/addmoney',
    add_money_short: '/am',
    manage_money_boxes: '/managemoneyboxes',
    manage_money_boxes_short: '/mmb',
    create_money_box: '/createmoneybox',
    add_money_to_box: '/addmoneytobox',
    add_all_money_to_box: '/addallmoneytobox',
    retire_money_from_box: '/retiremoneyfrombox',
    spend_money_from_box: '/spendmoneyfrombox',
    delete_money_box: '/deletemoneybox',
    manage_debts: '/managedebts',
    manage_debts_short: '/md',
    create_debt: '/createdebt',
    increase_debt: '/increasedebt',
    get_debt: '/takedebt',
    delete_debt: '/deletedebt',
    manage_monthly_taxes: '/managemonthlytaxes',
    manage_monthly_taxes_short: '/mmt',
    create_monthly_tax: '/createmonthlytax',
    money_to_monthly_taxes: '/moneytomonthlytaxes',
    money_from_monthly_taxes: '/moneyfrommonthlytaxes',
    delete_monthly_tax: '/deletemonthlytax',
    pay_monthly_tax: '/paymonthlytax',
    pay_all_monthly_taxes: '/payallmonthlytaxes',
    manage_yearly_taxes: '/manageyearlytaxes',
    manage_yearly_taxes_short: '/myt',
    create_yearly_tax:'/createyearlytax',
    money_to_yearly_taxes: '/moneytoyearlytaxes',
    money_from_yearly_taxes: '/moneyfromyearlytaxes',
    delete_yearly_tax: '/deleteyearlytax',
    pay_yearly_tax: '/payyearlytax',
    manage_other_taxes: '/manageothertaxes',
    manage_other_taxes_short: '/mot',
    create_other_tax:'/createothertax',
    money_to_other_taxes: '/moneytoothertaxes',
    money_from_other_taxes: '/moneyfromothertaxes',
    delete_other_tax: '/deleteothertax',
    pay_other_tax: '/payothertax',
    manage_future_purchases: '/managefuturepurchases',
    manage_future_purchases_short: '/mfp',
    add_future_purchase:'/addfuturepurchase',
    money_to_future_purchases: '/moneytofuturepurchases',
    money_from_future_purchases: '/moneyfromfuturepurchases',
    delete_future_purchase: '/deletefuturepurchase',
    perform_purchase: '/performpurchase',
    erase_all_data: '/erasedata',
    erase_all_data_short: '/ed',

}

module.exports = {
    Actions
}